# Generated by Django 3.2.8 on 2022-07-03 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220630_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminstrators',
            old_name='Id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='airline_compamies',
            old_name='Id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='countries',
            old_name='Id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='Id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='Id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='Id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='users_roles',
            old_name='Id',
            new_name='_id',
        ),
    ]
