# Generated by Django 3.2.8 on 2022-07-03 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20220703_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='User_Role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.users_roles'),
        ),
    ]
