# Generated by Django 3.2.8 on 2022-07-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_users_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_roles',
            name='Role_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
