# Generated by Django 3.2.8 on 2022-07-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220712_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='User',
            new_name='user',
        ),
    ]
