# Generated by Django 3.2.8 on 2022-07-12 15:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0012_auto_20220712_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airline_Companies',
            new_name='Airline_Compamies',
        ),
    ]
