# Generated by Django 3.2.8 on 2022-07-12 15:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0013_rename_airline_companies_airline_compamies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adminstrators',
            new_name='Adminstrator',
        ),
        migrations.RenameModel(
            old_name='Airline_Compamies',
            new_name='Airline_Compamie',
        ),
        migrations.RenameModel(
            old_name='Countries',
            new_name='Countrie',
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Flights',
            new_name='Flight',
        ),
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
        migrations.RenameModel(
            old_name='Users_Roles',
            new_name='Users_Role',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Customers',
            new_name='Customer',
        ),
    ]
