# Generated by Django 3.2.8 on 2022-08-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20220713_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='Price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='countrie',
            name='Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Credit_Card_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Phone_No',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
