# Generated by Django 3.2.8 on 2022-08-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_countrie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='number_of_tickets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
