# Generated by Django 3.2.8 on 2022-08-24 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_ticket_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.customer'),
        ),
    ]
