# Generated by Django 3.2.8 on 2022-08-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20220829_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
