# Generated by Django 3.2.8 on 2022-08-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_flight_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Credit_Card_No',
        ),
    ]
